### ISSUE TITLE
Crash with QGIS 2.5

### ISSUE THREAD

**Issue by borysiasty** [etiennesky/profiletool#28]
_Issue moved from hub.qgis.org
Bug report #11162 Added by @pcav 2014-09-08_

Starting the plugin causes QGIS dev to crash on Debian sid:

```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x00007f93ebbdd109 in __libc_waitpid (pid=26291, stat_loc=0x7fff5935bc7c, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:40
40 ../sysdeps/unix/sysv/linux/waitpid.c: File o directory non esistente.
[Current thread is 1 (Thread 0x7f93f453a8c0 (LWP 26266))]
#0 0x00007f93ebbdd109 in __libc_waitpid (pid=26291, stat_loc=0x7fff5935bc7c, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:40
resultvar = 0
oldtype = 0
#1 0x00000000004fe577 in qgisCrash(int) ()
No symbol table info available.
#2 <signal handler called>
No locals.
#3 0x00007f93ee5c5420 in QWidget::palette() const () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
No symbol table info available.
#4 0x00007f9356efe0fd in QwtPlot::setCanvasBackground(QColor const&) () from /usr/lib/libqwt-qt4.so.5
No symbol table info available.
#5 0x00007f9357216ca2 in ?? () from /usr/lib/python2.7/dist-packages/PyQt4/Qwt5/Qwt.so
No symbol table info available.
#6 0x00007f936d28af4c in PyEval_EvalFrameEx () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
No symbol table info available.
#7 0x00007f936d28b35d in PyEval_EvalFrameEx () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
No symbol table info available.
#8 0x00007f936d28b35d in PyEval_EvalFrameEx () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
No symbol table info available.
#9 0x00007f936d2f2da0 in PyEval_EvalCodeEx () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
No symbol table info available.
#10 0x00007f936d243ebc in ?? () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
No symbol table info available.
#11 0x00007f936d24c8f3 in PyObject_Call () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
No symbol table info available.
#12 0x00007f936d298195 in ?? () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
No symbol table info available.
#13 0x00007f936d24c8f3 in PyObject_Call () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
No symbol table info available.
#14 0x00007f936d2f22f7 in PyEval_CallObjectWithKeywords () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
No symbol table info available.
#15 0x00007f936cdd9ae0 in sip_api_invoke_slot_ex () from /usr/lib/python2.7/dist-packages/sip.so
No symbol table info available.
#16 0x00007f936cade082 in ?? () from /usr/lib/python2.7/dist-packages/PyQt4/QtCore.so
No symbol table info available.
#17 0x00007f936cade3cd in ?? () from /usr/lib/python2.7/dist-packages/PyQt4/QtCore.so
No symbol table info available.
#18 0x00007f936cadef7d in ?? () from /usr/lib/python2.7/dist-packages/PyQt4/QtCore.so
No symbol table info available.
#19 0x00007f93ef242ffb in QMetaObject::activate(QObject*, QMetaObject const*, int, void**) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
No symbol table info available.
#20 0x00007f93ee96d051 in QComboBox::currentIndexChanged(int) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
No symbol table info available.
#21 0x00007f93ee96d0f1 in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
No symbol table info available.
#22 0x00007f93ee96d45b in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
No symbol table info available.
#23 0x00007f93ee96d6bf in QComboBox::setCurrentIndex(int) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
No symbol table info available.
#24 0x00007f93ef242c5c in QMetaObject::activate(QObject*, QMetaObject const*, int, void**) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
No symbol table info available.
#25 0x00007f93ef28f054 in QAbstractItemModel::rowsInserted(QModelIndex const&, int, int) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
No symbol table info available.
#26 0x00007f93ef227092 in QAbstractItemModel::endInsertRows() () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
No symbol table info available.
#27 0x00007f93eeb3f8af in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
No symbol table info available.
#28 0x00007f93ee96e6d9 in QComboBox::insertItem(int, QIcon const&, QString const&, QVariant const&) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
No symbol table info available.
#29 0x00007f936c3eec80 in ?? () from /usr/lib/python2.7/dist-packages/PyQt4/QtGui.so
No symbol table info available.
#30 0x00007f936d28af4c in PyEval_EvalFrameEx () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
No symbol table info available.
#31 0x00007f936d28b35d in PyEval_EvalFrameEx () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
No symbol table info available.
#32 0x00007f936d2f2da0 in PyEval_EvalCodeEx () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
No symbol table info available.
#33 0x00007f936d243ebc in ?? () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
No symbol table info available.
#34 0x00007f936d24c8f3 in PyObject_Call () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
No symbol table info available.
#35 0x00007f936d298195 in ?? () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
No symbol table info available.
#36 0x00007f936d24c8f3 in PyObject_Call () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
No symbol table info available.
#37 0x00007f936d2f22f7 in PyEval_CallObjectWithKeywords () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
No symbol table info available.
#38 0x00007f936cdd9ae0 in sip_api_invoke_slot_ex () from /usr/lib/python2.7/dist-packages/sip.so
No symbol table info available.
#39 0x00007f936cade082 in ?? () from /usr/lib/python2.7/dist-packages/PyQt4/QtCore.so
No symbol table info available.
#40 0x00007f936cade3cd in ?? () from /usr/lib/python2.7/dist-packages/PyQt4/QtCore.so
No symbol table info available.
#41 0x00007f936cadef7d in ?? () from /usr/lib/python2.7/dist-packages/PyQt4/QtCore.so
No symbol table info available.
#42 0x00007f93ef242ffb in QMetaObject::activate(QObject*, QMetaObject const*, int, void**) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
No symbol table info available.
#43 0x00007f93ee57cb22 in QAction::triggered(bool) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
No symbol table info available.
#44 0x00007f93ee57e6c7 in QAction::activate(QAction::ActionEvent) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
No symbol table info available.
#45 0x00007f93ee9d209d in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
No symbol table info available.
#46 0x00007f93ee9d6a69 in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
No symbol table info available.
#47 0x00007f93ee5d63b8 in QWidget::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
No symbol table info available.
#48 0x00007f93ee9daa4b in QMenu::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
No symbol table info available.
#49 0x00007f93ee58331c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
No symbol table info available.
#50 0x00007f93ee589f7f in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
No symbol table info available.
#51 0x00007f93f05f9acb in QgsApplication::notify(QObject*, QEvent*) () from /usr/lib/libqgis_core.so.2.5.0
No symbol table info available.
#52 0x00007f93ef22dcad in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
No symbol table info available.
#53 0x00007f93ee5895af in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
No symbol table info available.
#54 0x00007f93ee60068d in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
No symbol table info available.
#55 0x00007f93ee5fecb2 in QApplication::x11ProcessEvent(_XEvent*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
No symbol table info available.
#56 0x00007f93ee627f92 in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
No symbol table info available.
#57 0x00007f93e99b5ecd in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#58 0x00007f93e99b61b8 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#59 0x00007f93e99b626c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#60 0x00007f93ef25d14d in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
No symbol table info available.
#61 0x00007f93ee628056 in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
No symbol table info available.
#62 0x00007f93ef22c801 in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
No symbol table info available.
#63 0x00007f93ef22cb65 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
No symbol table info available.
#64 0x00007f93ef2325c7 in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
No symbol table info available.
#65 0x00000000004f8ffb in main ()
No symbol table info available.
gdb returned 0
```

**Comment by borysiasty** [comment]
I believe it's fixed long time ago, or at least not reproducable with contemporary QGIS.
