### ISSUE TITLE
Profile tool plugin - python problem

### ISSUE THREAD

**Issue by borysiasty** [etiennesky/profiletool#29]
_Issue moved from hub.qgis.org
Bug report #11165 Added by @ghtmtt 2014-09-09_

When pushing the button "edit curves lines and axes parameters" it appears this error:

```
Errore durante l'esecuzione di codice Python:

Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/matplotlib/backends/backend_qt4.py", line 594, in edit_parameters
    figureoptions.figure_edit(axes, self)
  File "/usr/lib/pymodules/python2.7/matplotlib/backends/qt4_editor/figureoptions.py", line 134, in figure_edit
    icon=get_icon('qt4_editor_options.svg'), apply=apply_callback)
  File "/usr/lib/pymodules/python2.7/matplotlib/backends/qt4_editor/formlayout.py", line 544, in fedit
    dialog = FormDialog(data, title, comment, icon, parent, apply)
  File "/usr/lib/pymodules/python2.7/matplotlib/backends/qt4_editor/formlayout.py", line 461, in __init__
    self.formwidget.setup()
  File "/usr/lib/pymodules/python2.7/matplotlib/backends/qt4_editor/formlayout.py", line 433, in setup
    widget.setup()
  File "/usr/lib/pymodules/python2.7/matplotlib/backends/qt4_editor/formlayout.py", line 408, in setup
    widget.setup()
  File "/usr/lib/pymodules/python2.7/matplotlib/backends/qt4_editor/formlayout.py", line 315, in setup
    field.addItems(value)
TypeError: QComboBox.addItems(QStringList): argument 1 has unexpected type 'list'

Versione Python:
2.7.8 (default, Aug 24 2014, 09:51:25) 
[GCC 4.9.1]

Versione di QGIS:
2.5.0-Master Master, exported

Percorso Python: ['/home/ma7730/.qgis2/python/plugins/processing', '/home/ma7730/.qgis2/python/plugins/GeoCoding', '/usr/share/qgis/python', u'/home/ma7730/.qgis2/python', u'/home/ma7730/.qgis2/python/plugins', '/usr/share/qgis/python/plugins', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-i386-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/PILcompat', '/usr/lib/python2.7/dist-packages/gtk-2.0', '/usr/lib/pymodules/python2.7', '/usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode', '/usr/share/qgis/python/plugins/fTools/tools']
```

On debian testin and QGIS Master 2.5.

Cheers

**Comment by patricev** [comment]
matplotlib no more used...
