### ISSUE TITLE
error loading v. 4.0.1

### ISSUE THREAD

**Issue by adzane** [etiennesky/profiletool#36]
Hi, QGIS does not load profiletool 4.0.1 here (QGIS 2.14 on xubuntu trusty).
Traceback follows. Thanks!
---------------------------

Impossibile caricare il plugin profiletool a causa di un errore chiamando il metodo classFactory() 

NameError: name 'QtCore' is not defined 
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 306, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/pippo/.qgis2/python/plugins/profiletool/__init__.py", line 27, in classFactory
    from .profileplugin import ProfilePlugin
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 572, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/pippo/.qgis2/python/plugins/profiletool/profileplugin.py", line 42, in 
    from .tools.profiletool_core import ProfileToolCore
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 572, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/pippo/.qgis2/python/plugins/profiletool/tools/profiletool_core.py", line 42, in 
    from .ptmaptool import ProfiletoolMapTool, ProfiletoolMapToolRenderer
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 572, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/pippo/.qgis2/python/plugins/profiletool/tools/ptmaptool.py", line 197, in 
    class ProfiletoolMapTool(QgsMapTool):
  File "/home/pippo/.qgis2/python/plugins/profiletool/tools/ptmaptool.py", line 199, in ProfiletoolMapTool
    moved = QtCore.pyqtSignal(dict)
NameError: name 'QtCore' is not defined

Versione Python: 2.7.6 (default, Oct 26 2016, 20:36:21) [GCC 4.8.4] 
Versione di QGIS: 2.14.12-Essen Essen, exported 

Path di Python:
/usr/share/qgis/python/plugins/processing
/usr/share/qgis/python
/home/pippo/.qgis2/python
/home/pippo/.qgis2/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python2.7
/usr/lib/python2.7/plat-i386-linux-gnu
/usr/lib/python2.7/lib-tk
/usr/lib/python2.7/lib-old
/usr/lib/python2.7/lib-dynload
/usr/local/lib/python2.7/dist-packages
/usr/lib/python2.7/dist-packages
/usr/lib/python2.7/dist-packages/PILcompat
/usr/lib/python2.7/dist-packages/gtk-2.0
/usr/lib/pymodules/python2.7
/usr/lib/python2.7/dist-packages/ubuntu-sso-client
/usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode
/home/pippo/.qgis2//python
/usr/share/qgis/python/plugins/fTools/tools

**Comment by patricev** [comment]
Hi
I fixed the issue in the latest commit. Could you download the code and tell me if it's ok ?
Regards,

**Comment by adzane** [comment]
Yes, it works in Ubuntu now. I will test in Windows within some days.
