### ISSUE TITLE
Uncaught AttributeError: 'module' object has no attribute 'NavigationToolbar2QTAgg'


### ISSUE THREAD

**Issue by peter-shr** [etiennesky/profiletool#38]
Steps to reproduce
 1. First 
 2. Second 
 3. Third 

```
Traceback (most recent call last):
  File "C:/Users/USER/.qgis2/python/plugins\profiletool\ui\ptdockwidget.py", line 162, in changePlotLibrary
    self.addPlotWidget(self.plotlibrary)
  File "C:/Users/USER/.qgis2/python/plugins\profiletool\ui\ptdockwidget.py", line 229, in addPlotWidget
    mpltoolbar = matplotlib.backends.backend_qt4agg.NavigationToolbar2QTAgg(self.plotWdg, self.frame_for_plot)
AttributeError: 'module' object has no attribute 'NavigationToolbar2QTAgg'

```
profiletool 4.0.2, QGIS 2.14.14-Essen on Windows 10

**Comment by landryb** [comment]
The fix from BergWerkGIS/VoGIS-Profil-Tool#6 should be applied - it happens with matplotlib >= 1.5.
