### ISSUE TITLE
Couldn't load plugin processing

### ISSUE THREAD

**Issue by tveinot** [etiennesky/profiletool#42]
I have been using the profile tool for a while and suddenly now when I install it on 2.18.10 I get Couldn't load plugin processing. Also QField Sync and qgis2web stop working as well; all returns to normal when I uninstall the profile tool.
Below is a copy and past of what python says;

Couldn't load plugin qfieldsync due to an error when calling its classFactory() method 

ImportError: cannot import name uic 
Traceback (most recent call last):
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 333, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/tveinot/.qgis2/python/plugins\qfieldsync\__init__.py", line 70, in classFactory
    from qfieldsync.qfield_sync import QFieldSync
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/tveinot/.qgis2/python/plugins\qfieldsync\qfield_sync.py", line 26, in 
    from qfieldsync.core import Preferences
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/tveinot/.qgis2/python/plugins\qfieldsync\core\__init__.py", line 4, in 
    from .offline_converter import OfflineConverter  # NOQA
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/tveinot/.qgis2/python/plugins\qfieldsync\core\offline_converter.py", line 25, in 
    import processing
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/OSGEO4~1/apps/qgis/./python/plugins\processing\__init__.py", line 29, in 
    from processing.tools.general import *              # NOQA
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/OSGEO4~1/apps/qgis/./python/plugins\processing\tools\general.py", line 31, in 
    from processing.core.Processing import Processing
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/OSGEO4~1/apps/qgis/./python/plugins\processing\core\Processing.py", line 42, in 
    from processing.script.ScriptUtils import ScriptUtils
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/OSGEO4~1/apps/qgis/./python/plugins\processing\script\ScriptUtils.py", line 30, in 
    from processing.script.ScriptAlgorithm import ScriptAlgorithm
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/OSGEO4~1/apps/qgis/./python/plugins\processing\script\ScriptAlgorithm.py", line 34, in 
    from processing.gui.Help2Html import getHtmlFromHelpFile
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/OSGEO4~1/apps/qgis/./python/plugins\processing\gui\__init__.py", line 1, in 
    from qgis.PyQt import uic
ImportError: cannot import name uic

Python version: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
QGIS version: 2.18.10 Las Palmas, 59e0f78 

Python Path:
C:/OSGEO4~1/apps/qgis/./python
C:/Users/tveinot/.qgis2/python
C:/Users/tveinot/.qgis2/python/plugins
C:/OSGEO4~1/apps/qgis/./python/plugins
C:\OSGEO4~1\bin\python27.zip
C:\OSGEO4~1\apps\Python27\DLLs
C:\OSGEO4~1\apps\Python27\lib
C:\OSGEO4~1\apps\Python27\lib\plat-win
C:\OSGEO4~1\apps\Python27\lib\lib-tk
C:\OSGEO4~1\bin
C:\OSGEO4~1\apps\Python27
C:\OSGEO4~1\apps\Python27\lib\site-packages
C:\OSGEO4~1\apps\Python27\lib\site-packages\jinja2-2.7.2-py2.7.egg
C:\OSGEO4~1\apps\Python27\lib\site-packages\markupsafe-0.23-py2.7-win-amd64.egg
C:\OSGEO4~1\apps\Python27\lib\site-packages\win32
C:\OSGEO4~1\apps\Python27\lib\site-packages\win32\lib
C:\OSGEO4~1\apps\Python27\lib\site-packages\Pythonwin
C:\OSGEO4~1\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win-amd64.egg
C:\OSGEO4~1\apps\Python27\lib\site-packages\wx-2.8-msw-unicode
C:\OSGEO4~1\apps\Python27\lib\site-packages\xlrd-0.9.2-py2.7.egg
C:\OSGEO4~1\apps\Python27\lib\site-packages\xlwt-0.7.5-py2.7.egg
C:/Users/tveinot/.qgis2//python
C:\Users\tveinot\.qgis2\python\plugins\DigitizingTools\tools
C:\Users\tveinot\.qgis2\python\plugins\mmqgis/forms

2017-07-19T15:45:58	0	QGIS starting...
2017-07-19T15:45:58	0	Python support ENABLED :-) 
2017-07-19T15:46:02	0	Application state:
			QGIS_PREFIX_PATH env var:		C:/OSGEO4~1/apps/qgis
			Prefix:		C:/OSGEO4~1/apps/qgis
			Plugin Path:		C:/OSGEO4~1/apps/qgis/plugins
			Package Data Path:	C:/OSGEO4~1/apps/qgis/.
			Active Theme Name:	default
			Active Theme Path:	C:/Users/tveinot/.qgis2///themes\default\icons/
			Default Theme Path:	:/images/themes/default/
			SVG Search Paths:	C:/OSGEO4~1/apps/qgis/./svg/
					C:/Users/tveinot/.qgis2//svg/
					C:/PROGRA~1/QGIS2~1.16/apps/qgis/./svg/
			User DB Path:	C:/OSGEO4~1/apps/qgis/./resources/qgis.db
			Auth DB Path:	C:/Users/tveinot/.qgis2//qgis-auth.db
			
2017-07-19T15:46:02	0	QGIS Ready!

2017-07-19T15:45:58	0	Loaded Coordinate Capture (Path: C:/OSGEO4~1/apps/qgis/plugins/coordinatecaptureplugin.dll)
2017-07-19T15:45:58	0	Loaded Dxf2Shp Converter (Path: C:/OSGEO4~1/apps/qgis/plugins/dxf2shpconverterplugin.dll)
2017-07-19T15:45:58	0	Loaded eVis (Path: C:/OSGEO4~1/apps/qgis/plugins/evis.dll)
2017-07-19T15:45:58	0	Loaded Geometry Checker (Path: C:/OSGEO4~1/apps/qgis/plugins/geometrycheckerplugin.dll)
2017-07-19T15:45:58	0	Loaded Geometry Snapper (Path: C:/OSGEO4~1/apps/qgis/plugins/geometrysnapperplugin.dll)
2017-07-19T15:45:58	0	Loaded Georeferencer GDAL (Path: C:/OSGEO4~1/apps/qgis/plugins/georefplugin.dll)
2017-07-19T15:45:58	1	Failed to load C:/OSGEO4~1/apps/qgis/plugins/globeplugin.dll (Reason: Cannot load library C:/OSGEO4~1/apps/qgis/plugins/globeplugin.dll: The specified module could not be found.)
2017-07-19T15:45:58	0	Loaded GPS Tools (Path: C:/OSGEO4~1/apps/qgis/plugins/gpsimporterplugin.dll)
2017-07-19T15:45:59	0	Loaded GRASS 7 (Path: C:/OSGEO4~1/apps/qgis/plugins/grassplugin7.dll)
2017-07-19T15:45:59	0	Loaded Heatmap (Path: C:/OSGEO4~1/apps/qgis/plugins/heatmapplugin.dll)
2017-07-19T15:45:59	0	Loaded Interpolation plugin (Path: C:/OSGEO4~1/apps/qgis/plugins/interpolationplugin.dll)
2017-07-19T15:45:59	0	Loaded OfflineEditing (Path: C:/OSGEO4~1/apps/qgis/plugins/offlineeditingplugin.dll)
2017-07-19T15:45:59	0	Loaded Oracle Spatial GeoRaster (Path: C:/OSGEO4~1/apps/qgis/plugins/oracleplugin.dll)
2017-07-19T15:45:59	0	Loaded Raster Terrain Analysis plugin (Path: C:/OSGEO4~1/apps/qgis/plugins/rasterterrainplugin.dll)
2017-07-19T15:45:59	0	Loaded Road graph plugin (Path: C:/OSGEO4~1/apps/qgis/plugins/roadgraphplugin.dll)
2017-07-19T15:45:59	0	Loaded Spatial Query Plugin (Path: C:/OSGEO4~1/apps/qgis/plugins/spatialqueryplugin.dll)
2017-07-19T15:45:59	0	Loaded Topology Checker (Path: C:/OSGEO4~1/apps/qgis/plugins/topolplugin.dll)
2017-07-19T15:45:59	0	Loaded Zonal statistics plugin (Path: C:/OSGEO4~1/apps/qgis/plugins/zonalstatisticsplugin.dll)
2017-07-19T15:45:59	0	Loaded AutoFields (package: AutoFields)
2017-07-19T15:45:59	0	Loaded changeDataSource (package: changeDataSource)
2017-07-19T15:45:59	0	Loaded Digitizing Tools (package: DigitizingTools)
2017-07-19T15:45:59	0	Loaded go2streetview (package: go2streetview)
2017-07-19T15:45:59	0	Loaded Instant Print (package: instantprint)
2017-07-19T15:46:00	0	Loaded Intersect It (package: intersectit)
2017-07-19T15:46:00	0	Loaded mmqgis (package: mmqgis)
2017-07-19T15:46:00	0	Loaded MultiEdit (package: MultiEdit)
2017-07-19T15:46:00	0	Loaded PgVersion (package: pgversion)
2017-07-19T15:46:00	0	Loaded Profile tool (package: profiletool)
2017-07-19T15:46:00	0	Loaded QAD (package: qad)
2017-07-19T15:46:01	0	Loaded QField Sync (package: qfieldsync)
2017-07-19T15:46:01	0	Loaded QGIS2compat (package: qgis2compat)
2017-07-19T15:46:01	0	Loaded Qgis2threejs (package: Qgis2threejs)
2017-07-19T15:46:01	0	Loaded qgis2web (package: qgis2web)
2017-07-19T15:46:01	0	Loaded Quick Draw (package: quickdraw)
2017-07-19T15:46:01	0	Loaded Quick Finder (package: quickfinder)
2017-07-19T15:46:01	0	Loaded QuickMultiAttributeEdit (package: QuickMultiAttributeEdit)
2017-07-19T15:46:01	0	Loaded Smart editing tools (package: smart-editing-tools)
2017-07-19T15:46:01	0	Loaded DB Manager (package: db_manager)
2017-07-19T15:46:01	0	Loaded GdalTools (package: GdalTools)
2017-07-19T15:46:01	0	Loaded MetaSearch Catalogue Client (package: MetaSearch)
2017-07-19T15:46:01	0	Loaded Processing (package: processing)

2017-07-19T15:46:01	1	Traceback (most recent call last):
			  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 333, in startPlugin
			    plugins[packageName] = package.classFactory(iface)
			  File "C:/Users/tveinot/.qgis2/python/plugins\qfieldsync\__init__.py", line 70, in classFactory
			    from qfieldsync.qfield_sync import QFieldSync
			  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:/Users/tveinot/.qgis2/python/plugins\qfieldsync\qfield_sync.py", line 26, in <module>
			    from qfieldsync.core import Preferences
			  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:/Users/tveinot/.qgis2/python/plugins\qfieldsync\core\__init__.py", line 4, in <module>
			    from .offline_converter import OfflineConverter  # NOQA
			  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:/Users/tveinot/.qgis2/python/plugins\qfieldsync\core\offline_converter.py", line 25, in <module>
			    import processing
			  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:/OSGEO4~1/apps/qgis/./python/plugins\processing\__init__.py", line 29, in <module>
			    from processing.tools.general import *              # NOQA
			  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:/OSGEO4~1/apps/qgis/./python/plugins\processing\tools\general.py", line 31, in <module>
			    from processing.core.Processing import Processing
			  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:/OSGEO4~1/apps/qgis/./python/plugins\processing\core\Processing.py", line 42, in <module>
			    from processing.script.ScriptUtils import ScriptUtils
			  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:/OSGEO4~1/apps/qgis/./python/plugins\processing\script\ScriptUtils.py", line 30, in <module>
			    from processing.script.ScriptAlgorithm import ScriptAlgorithm
			  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:/OSGEO4~1/apps/qgis/./python/plugins\processing\script\ScriptAlgorithm.py", line 34, in <module>
			    from processing.gui.Help2Html import getHtmlFromHelpFile
			  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:/OSGEO4~1/apps/qgis/./python/plugins\processing\gui\__init__.py", line 1, in <module>
			    from qgis.PyQt import uic
			ImportError: cannot import name uic
			
2017-07-19T15:46:01	1	Traceback (most recent call last):
			  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 333, in startPlugin
			    plugins[packageName] = package.classFactory(iface)
			  File "C:/Users/tveinot/.qgis2/python/plugins\qgis2web\__init__.py", line 28, in classFactory
			    from .qgis2web import Qgis2Web
			  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:/Users/tveinot/.qgis2/python/plugins\qgis2web\qgis2web.py", line 25, in <module>
			    from processing.core.Processing import Processing
			  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:/OSGEO4~1/apps/qgis/./python/plugins\processing\__init__.py", line 29, in <module>
			    from processing.tools.general import *              # NOQA
			  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:/OSGEO4~1/apps/qgis/./python/plugins\processing\tools\general.py", line 31, in <module>
			    from processing.core.Processing import Processing
			  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:/OSGEO4~1/apps/qgis/./python/plugins\processing\core\Processing.py", line 42, in <module>
			    from processing.script.ScriptUtils import ScriptUtils
			  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:/OSGEO4~1/apps/qgis/./python/plugins\processing\script\ScriptUtils.py", line 30, in <module>
			    from processing.script.ScriptAlgorithm import ScriptAlgorithm
			  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:/OSGEO4~1/apps/qgis/./python/plugins\processing\script\ScriptAlgorithm.py", line 34, in <module>
			    from processing.gui.Help2Html import getHtmlFromHelpFile
			  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:/OSGEO4~1/apps/qgis/./python/plugins\processing\gui\__init__.py", line 1, in <module>
			    from qgis.PyQt import uic
			ImportError: cannot import name uic
			
2017-07-19T15:46:01	1	Traceback (most recent call last):
			  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 308, in loadPlugin
			    __import__(packageName)
			  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:/OSGEO4~1/apps/qgis/./python/plugins\processing\__init__.py", line 29, in <module>
			    from processing.tools.general import *              # NOQA
			  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:/OSGEO4~1/apps/qgis/./python/plugins\processing\tools\general.py", line 31, in <module>
			    from processing.core.Processing import Processing
			  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:/OSGEO4~1/apps/qgis/./python/plugins\processing\core\Processing.py", line 42, in <module>
			    from processing.script.ScriptUtils import ScriptUtils
			  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:/OSGEO4~1/apps/qgis/./python/plugins\processing\script\ScriptUtils.py", line 30, in <module>
			    from processing.script.ScriptAlgorithm import ScriptAlgorithm
			  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:/OSGEO4~1/apps/qgis/./python/plugins\processing\script\ScriptAlgorithm.py", line 34, in <module>
			    from processing.gui.Help2Html import getHtmlFromHelpFile
			  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:/OSGEO4~1/apps/qgis/./python/plugins\processing\gui\__init__.py", line 1, in <module>
			    from qgis.PyQt import uic
			ImportError: cannot import name uic

**Comment by tveinot** [comment]
I solved it, entirely my fault.
