### ISSUE TITLE
Edit Curves and Axes Parameters

### ISSUE THREAD

**Issue by rjhale1971** [etiennesky/profiletool#9]
I'm on Ubuntu 14.04. If I create a profile then press the edit Lines and Axes Button I get an error: 

An error has occured while executing Python code:

Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/matplotlib/backends/backend_qt4.py", line 594, in edit_parameters
    figureoptions.figure_edit(axes, self)
  File "/usr/lib/pymodules/python2.7/matplotlib/backends/qt4_editor/figureoptions.py", line 134, in figure_edit
    icon=get_icon('qt4_editor_options.svg'), apply=apply_callback)
  File "/usr/lib/pymodules/python2.7/matplotlib/backends/qt4_editor/formlayout.py", line 544, in fedit
    dialog = FormDialog(data, title, comment, icon, parent, apply)
  File "/usr/lib/pymodules/python2.7/matplotlib/backends/qt4_editor/formlayout.py", line 461, in __init__
    self.formwidget.setup()
  File "/usr/lib/pymodules/python2.7/matplotlib/backends/qt4_editor/formlayout.py", line 433, in setup
    widget.setup()
  File "/usr/lib/pymodules/python2.7/matplotlib/backends/qt4_editor/formlayout.py", line 408, in setup
    widget.setup()
  File "/usr/lib/pymodules/python2.7/matplotlib/backends/qt4_editor/formlayout.py", line 315, in setup
    field.addItems(value)
TypeError: QComboBox.addItems(QStringList): argument 1 has unexpected type 'list'

Python version:
2.7.6 (default, Mar 22 2014, 23:03:41) 
[GCC 4.8.2]

QGIS version:
2.8.1-Wien Wien, exported

Python path: ['/home/rjhale/.qgis2/python/plugins/processing', '/usr/share/qgis/python', u'/home/rjhale/.qgis2/python', u'/home/rjhale/.qgis2/python/plugins', '/usr/share/qgis/python/plugins', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/PILcompat', '/usr/lib/python2.7/dist-packages/gst-0.10', '/usr/lib/python2.7/dist-packages/gtk-2.0', '/usr/lib/pymodules/python2.7', '/usr/lib/python2.7/dist-packages/ubuntu-sso-client', '/usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode', u'/home/rjhale/.qgis2//python', '/home/rjhale/.qgis2/python/plugins/DigitizingTools/tools', '/usr/share/qgis/python/plugins/fTools/tools', '/home/rjhale/.qgis2/python/plugins/mmqgis/forms']

**Comment by etiennesky** [comment]
this is a matplotlib error, please add a bug report on the matplotlib project.
